doctrine_migrations:
    migrations_paths:
        App\Infrastructure\Shared\Persistence\Doctrine\Migrations: '%kernel.project_dir%/src/Infrastructure/Shared/Persistence/Doctrine/Migrations'
    enable_profiler: '%kernel.debug%'
