security:
    enable_authenticator_manager: true

    password_hashers:
        hasher:
            id: App\Infrastructure\User\Auth\PasswordHasher

    providers:
        users:
            id: 'App\Infrastructure\User\Auth\AuthProvider'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_status:
            pattern:  ^/status
            stateless: true

        api_doc:
            pattern:  ^/api/doc
            stateless: true

        api_auth:
            pattern:  ^/api/auth
            stateless: true

        api_signup:
            pattern:  ^/api/signup
            stateless: true

        api_secured:
            pattern:  ^/api
            provider: users
            stateless: true
            jwt: ~

        secured_area:
            pattern: ^/
            provider: users
            custom_authenticators:
                - 'App\Infrastructure\User\Auth\Guard\LoginAuthenticator'
            form_login:
                login_path: /sign-in
                check_path: sign-in
            entry_point: form_login
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/profile,     roles: ROLE_USER }
#        - { path: ^/status,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/auth,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/signup,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/doc,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/,        roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/,            roles: IS_AUTHENTICATED_ANONYMOUSLY }
