security:
    enable_authenticator_manager: true

    password_hashers:
        hasher:
            id: App\Infrastructure\User\Auth\PasswordHasher

    providers:
        users:
            id: 'App\Infrastructure\User\Auth\AuthProvider'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_status:
            pattern:  ^/status
            stateless: true

        api_doc:
            pattern:  ^/api/doc
            stateless: true

        api_auth:
            pattern:  ^/api/auth
            stateless: true

        api_signup:
            pattern:  ^/api/signup
            stateless: true

        api_secured:
            pattern:  ^/api
            provider: users
            stateless: true
            jwt: ~

        secured_area:
            pattern: ^/
            provider: users
            custom_authenticators:
                - 'App\Infrastructure\User\Auth\Guard\LoginAuthenticator'
            form_login:
                login_path: /sign-in
                check_path: sign-in
            entry_point: form_login
            logout:
                path: /logout
                target: /

    access_control:
        #API SCOPE
        - { path: ^/api/admin,    roles: ROLE_ADMIN }
        - { path: ^/api/user,    roles: ROLE_USER }
        #WEB SCOPE
        - { path: ^/profile,     roles: ROLE_USER }
        - { path: ^/user,    roles: ROLE_USER }
