version: '3.7'

services:

  mysql:
    ports:
      - "3306:3306"

  rmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    ports:
      - 5601:5601
    volumes:
      - "./etc/dev/kibana-conf:/usr/share/kibana/config/kibana.yml"

  elasticsearch:
    ports:
      - "9200:9200"

volumes:
  db_data:
