parameters:
    exception_to_status:
        InvalidArgumentException: 400
        App\Domain\User\Exception\InvalidCredentialsException: 401
        App\Domain\User\Exception\ForbiddenException: 403
        App\Infrastructure\Shared\Persistence\ReadModel\Exception\NotFoundException: 404
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        App\Application\Command\CommandHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.command }

        App\Application\Query\QueryHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.query }

    App\:
        resource: '../src/*'
        exclude:
            - '../src/Tests/'

    App\UI\Console\Command\:
        resource: '../src/UI/Console/Command/*'
        tags: [ 'controller.service_arguments' ]

    App\UI\Http\Rest\Controller\:
        resource: '../src/UI/Http/Rest/Controller/*'
        tags: ['controller.service_arguments']

    App\UI\Http\Web\Controller\:
        resource: '../src/UI/Http/Web/Controller/*'
        tags: ['controller.service_arguments']

    App\Infrastructure\Shared\Bus\Command\MessengerCommandBus:
        arguments:
            - '@messenger.bus.command'
    App\Infrastructure\Shared\Bus\Query\MessengerQueryBus:
        arguments:
            - '@messenger.bus.query'


